// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func LoginForm(err error) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"form-div\" hx-swap-oob=\"true\"><h3 class=\"text-green-400 text-1xl p-2 text-center\">LOGIN</h3><form id=\"form\" hx-post=\"/auth\" class=\"flex flex-col items-center\"><div class=\"relative w-full text-white\"><input type=\"text\" id=\"username\" name=\"username\" class=\"bg-black w-full pl-2 pr-10 py-2 rounded focus:outline-none focus:ring-2 focus:ring-blue-500 cursor-blink\" placeholder=\"Join room as\" autocomplete=\"off\" required></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if err != nil {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<p id=\"error\" class=\"text-red-400 p-1\">User doesn't exist. Please try again</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex w-full mt-4 space-x-4\"><button type=\"submit\" class=\"flex-grow bg-transparent py-2 rounded text-green-500 border border-solid border-green-500 hover:bg-green-500 hover:text-gray-900 focus:outline-none focus:bg-green-700\">Submit</button> <button hx-get=\"/register\" type=\"button\" class=\"flex-grow bg-transparent py-2 rounded text-yellow-500 border border-solid border-yellow-500 hover:bg-yellow-500 hover:text-gray-900 focus:outline-none focus:bg-green-700\">Register</button></div></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
