// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func RegisterUnsuccessful() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"form-div\" hx-swap-oob=\"true\"><form id=\"form\" hx-post=\"/register\" class=\"flex flex-col items-center\"><div class=\"relative w-full text-white\"><input type=\"text\" id=\"username\" name=\"username\" class=\"bg-black w-full pl-2 pr-10 py-2 rounded focus:outline-none focus:ring-2 focus:ring-blue-500 cursor-blink\" placeholder=\"Join room as\" autocomplete=\"off\" required></div><p class=\"text-red-400 p-2\">User already exists. Please try with another name</p><button type=\"submit\" class=\"w-full bg-green-600 mt-4 py-2 rounded text-white hover:bg-green-700 focus:outline-none focus:bg-green-700\">Submit</button></form><button type=\"submit\" class=\"w-full bg-green-600 mt-4 py-2 rounded text-white hover:bg-green-700 focus:outline-none focus:bg-green-700\">Login</button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
